layout_spectrum: 1
typography_spectrum: 0.9408602
color:
  saturation: 0.4444444
  lightness: 0.2508961
  brandStrength: 0.1068726
  brandColors:
    - '#A5C3E9'
    - '#98A6AF'
    - '#605C59'
    - '#392A2D'
    - '#EBBEA6'
  rhythmicContrast: 0.483871
name: Hippieshack
